# Generated by Django 4.2.10 on 2024-02-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeclock',
            name='clock_in_time',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='clock_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
